hospital/urls.py
from django.conf.urls import url, include
from django.contrib.admin.views.decorators import staff_member_required

from django.contrib.auth.decorators import login_required

from . import views

app_name = 'hospital'
urlpatterns = [

    url(r'^list/$',
        login_required(views.HospitalListView.as_view()),
        name="list"),

    url(r'^create/$',
        login_required(views.HospitalCreateView.as_view()),
        name="create"),
    
    url(r'^detail/(?P<pk>[0-9]+)$',
        login_required(views.HospitalDetailView.as_view()),
        name="detail"),

    url(r'^update/(?P<pk>[0-9]+)$',
        login_required(views.HospitalUpdateView.as_view()),
        name="update"),

    # Admin

    url(r'^equipment/list$',
        staff_member_required(views.EquipmentAdminListView.as_view()),
        name='equipment_list'),

    url(r'^equipment/create$',
        staff_member_required(views.EquipmentAdminCreateView.as_view()),
        name='equipment_create'),

    url(r'^equipment/detail/(?P<pk>[0-9]+)$',
        staff_member_required(views.EquipmentAdminDetailView.as_view()),
        name='equipment_detail'),

    url(r'^equipment/update/(?P<pk>[0-9]+)$',
        staff_member_required(views.EquipmentAdminUpdateView.as_view()),
        name='equipment_update'),

]

login/urls.py
from django.conf.urls import url
from django.contrib.admin.views.decorators import staff_member_required

from login import views

app_name = 'login'
urlpatterns = [

    # login/logout
    url(r'^login/$',
        views.LoginView.as_view(),
        name='login'),
    url(r'^logout/$',
        views.LogoutView.as_view(),
        name='logout'),

    # signup
    url(r'^signup/$',
        views.SignupView.as_view(),
        name='signup'),
    
    # User Admin
    
    url(r'^user/$',
        staff_member_required(views.UserAdminListView.as_view()),
        name='user_list'),

    url(r'^user/create/$',
        staff_member_required(views.UserAdminCreateView.as_view()),
        name='user_create'),

    url(r'^user/detail/(?P<pk>[0-9]+)$',
        staff_member_required(views.UserAdminDetailView.as_view()),
        name='user_detail'),

    url(r'^user/update/(?P<pk>[0-9]+)$',
        staff_member_required(views.UserAdminUpdateView.as_view()),
        name='user_update'),

    # Group Admin

    url(r'^group/$',
        staff_member_required(views.GroupAdminListView.as_view()),
        name='group_list'),

    url(r'^group/create/$',
        staff_member_required(views.GroupAdminCreateView.as_view()),
        name='group_create'),

    url(r'^group/detail/(?P<pk>[0-9]+)$',
        staff_member_required(views.GroupAdminDetailView.as_view()),
        name='group_detail'),

    url(r'^group/update/(?P<pk>[0-9]+)$',
        staff_member_required(views.GroupAdminUpdateView.as_view()),
        name='group_update'),

    # client admin
    url(r'^client/$',
        staff_member_required(views.ClientListView.as_view()),
        name='client_list'),

    url(r'^client/detail/(?P<pk>[0-9]+)$',
        staff_member_required(views.ClientDetailView.as_view()),
        name='client_detail'),

    # restart

    url(r'^restart/$',
        views.RestartView.as_view(),
        name='restart'),

    # mqtt login
    
    url(r'^mqtt/login/$',
        views.MQTTLoginView.as_view(),
        name='mqtt_login'),
    url(r'^mqtt/superuser/$',
        views.MQTTSuperuserView.as_view(),
        name='mqtt_superuser'),
    url(r'^mqtt/acl/$',
        views.MQTTAclView.as_view(),
        name='mqtt_acl'),
    
]

hospital/models.py
from enum import Enum

from django.urls import reverse
from django.contrib.gis.db import models
from django.template.defaulttags import register

from emstrack.models import AddressModel, UpdatedByModel


# filters

@register.filter
def get_equipment_type(type):
    return EquipmentType[type].value


# Hospital model

class Hospital(AddressModel,
               UpdatedByModel):
    name = models.CharField(max_length=254, unique=True)

    def save(self, *args, **kwargs):

        # creation?
        created = self.pk is None

        # save to Hospital
        super().save(*args, **kwargs)

        # publish to mqtt
        from mqtt.publish import SingletonPublishClient
        SingletonPublishClient().publish_hospital(self)

        # just created?
        if created:
            # invalidate permissions cache
            from login.permissions import cache_clear
            cache_clear()

    def delete(self, *args, **kwargs):

        # remove from mqtt
        from mqtt.publish import SingletonPublishClient
        SingletonPublishClient().remove_hospital(self)

        # invalidate permissions cache
        from login.permissions import cache_clear
        cache_clear()

        # delete from Hospital
        super().delete(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('hospital:detail', kwargs={'pk': self.id})

    def __str__(self):
        return ('Hospital {}(id={})\n' +
                '   Address: {} {} {}\n' +
                '            {} {} {}\n' +
                '            {} \n' +
                '  Location: {}\n' +
                '   Comment: {}\n' +
                '   Updated: {} by {}').format(self.name,
                                               self.id,
                                               self.number,
                                               self.street,
                                               self.unit,
                                               self.city,
                                               self.state,
                                               self.zipcode,
                                               self.country,
                                               self.location,
                                               self.comment,
                                               self.updated_by,
                                               self.updated_on)


class EquipmentType(Enum):
    B = 'Boolean'
    I = 'Integer'
    S = 'String'


class Equipment(models.Model):
    name = models.CharField(max_length=254, unique=True)

    EQUIPMENT_TYPE_CHOICES = \
        [(m.name, m.value) for m in EquipmentType]
    type = models.CharField(max_length=1,
                            choices=EQUIPMENT_TYPE_CHOICES)

    def __str__(self):
        return "{} ({})".format(self.name, self.type)

    def get_absolute_url(self):
        return reverse('hospital:equipment_detail', kwargs={'pk': self.id})


class HospitalEquipment(UpdatedByModel):
    hospital = models.ForeignKey(Hospital,
                                 on_delete=models.CASCADE)
    equipment = models.ForeignKey(Equipment,
                                  on_delete=models.CASCADE)
    value = models.CharField(max_length=254)

    def save(self, *args, **kwargs):

        # creation?
        created = self.pk is None

        # save to HospitalEquipment
        super().save(*args, **kwargs)
        from mqtt.publish import SingletonPublishClient

        # publish to mqtt
        client = SingletonPublishClient()
        client.publish_hospital_equipment(self)
        if created:
            client.publish_hospital_metadata(self.hospital)

    def delete(self, *args, **kwargs):

        # remove from mqtt
        from mqtt.publish import SingletonPublishClient
        client = SingletonPublishClient()
        client.remove_hospital_equipment(self)
        client.publish_hospital_metadata(self.hospital)

        # delete from HospitalEquipment
        super().delete(*args, **kwargs)

    class Meta:
        unique_together = ('hospital', 'equipment',)

    def __str__(self):
        return "Hospital: {}, Equipment: {}, Count: {}".format(self.hospital, self.equipment, self.value)

hospital/forms.py
from django import forms
from django.contrib.gis.forms import PointField

from emstrack.forms import LeafletPointWidget

from .models import Hospital


class HospitalCreateForm(forms.ModelForm):
    location = PointField(
        widget=LeafletPointWidget(attrs={'map_width': 500,
                                         'map_height': 300})
    )

    class Meta:
        model = Hospital
        fields = ['name',
                  'number', 'street', 'unit', 'neighborhood',
                  'city', 'state', 'zipcode', 'country',
                  'location', 'comment']


class HospitalUpdateForm(HospitalCreateForm):
    pass

hospital/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.views.generic import ListView, DetailView, CreateView, UpdateView

from extra_views import InlineFormSet, CreateWithInlinesView, \
    UpdateWithInlinesView

from .models import Hospital, HospitalEquipment, Equipment

from .forms import HospitalCreateForm, HospitalUpdateForm

from emstrack.mixins import BasePermissionMixin, SuccessMessageWithInlinesMixin, UpdatedByWithInlinesMixin


# Django views


class HospitalPermissionMixin(BasePermissionMixin):

    filter_field = 'id'
    profile_field = 'hospitals'
    queryset = Hospital.objects.all()


class HospitalEquipmentInline(InlineFormSet):
    model = HospitalEquipment
    fields = ['equipment', 'value', 'comment']
    extra = 1


class HospitalCreateView(LoginRequiredMixin,
                         SuccessMessageWithInlinesMixin,
                         UpdatedByWithInlinesMixin,
                         HospitalPermissionMixin,
                         CreateWithInlinesView):
    model = Hospital
    inlines = [HospitalEquipmentInline]
    form_class = HospitalCreateForm

    def get_success_message(self, cleaned_data):
        return "Successfully created hospital '{}'".format(cleaned_data['name'])

    def get_success_url(self):
        return self.object.get_absolute_url()


class HospitalUpdateView(LoginRequiredMixin,
                         SuccessMessageWithInlinesMixin,
                         UpdatedByWithInlinesMixin,
                         HospitalPermissionMixin,
                         UpdateWithInlinesView):
    model = Hospital
    inlines = [HospitalEquipmentInline]
    form_class = HospitalUpdateForm

    def get_success_message(self, cleaned_data):
        return "Successfully updated hospital '{}'".format(cleaned_data['name'])

    def get_success_url(self):
        return self.object.get_absolute_url()


class HospitalDetailView(LoginRequiredMixin,
                         HospitalPermissionMixin,
                         DetailView):

    model = Hospital


class HospitalListView(LoginRequiredMixin,
                       HospitalPermissionMixin,
                       ListView):

    model = Hospital
    ordering = ['name']


# HospitalEquipment

class EquipmentAdminListView(ListView):
    model = Equipment
    ordering = ['name']


class EquipmentAdminDetailView(DetailView):
    model = Equipment


class EquipmentAdminCreateView(SuccessMessageMixin,
                               CreateView):
    model = Equipment
    fields = ['name', 'type']

    def get_success_message(self, cleaned_data):
        return "Successfully created equipment '{}'".format(self.object.name)

    def get_success_url(self):
        return self.object.get_absolute_url()


class EquipmentAdminUpdateView(SuccessMessageMixin,
                               UpdateView):
    model = Equipment
    fields = ['name', 'type']

    def get_success_message(self, cleaned_data):
        return "Successfully updated equipment '{}'".format(self.object.name)

    def get_success_url(self):
        return self.object.get_absolute_url()

templates/hospital/equipment_detail.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col">

            <h1>Hospital Equipment</h1>

            <h3>Details:</h3>

            <p>
                <strong>Name:</strong>
                <a href="{% url 'hospital:equipment_update' pk=equipment.id %}">{{ equipment.name }}</a>
            </p>
            <p>
                <strong>Type:</strong>
                {{ equipment.type|get_equipment_type }}
            </p>
        </div>
    </div>
</div>

{% endblock %}

templates/hospital/equipment_form.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col">

            <h1>Hospital Equipment</h1>

            <form method="POST" class="post-form">
                {% csrf_token %}

                <h3>Details:</h3>

                <table>
                    {{ form }}
                </table>

                <p>
                    <button type="submit" class="btn btn-primary">Save</button>
                </p>
            </form>
        </div>
    </div>
</div>

{% endblock %}

templates/hospital/equipment_list.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-md-6">

            <h1>Hospital Equipment</h1>

            <p>
                <a href="{% url 'hospital:equipment_create' %}">new</a>
            </p>
            <table class="table table-striped table-sm">
                <thead>
                <tr>
                    <th>Name</th>
                    <th>Type</th>
                </tr>
                </thead>
                <tbody>
                {% for equipment in equipment_list %}
                <tr>
                    <td>
                        <a href="{% url 'hospital:equipment_detail' pk=equipment.id %}">{{ equipment.name }}</a>
                    </td>
                    <td>
                        {{ equipment.type|get_equipment_type }}
                    </td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

{% endblock %}

templates/hospital/hospital_detail.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col">

            <h1>Hospital</h1>

            <h3>
                Details:
            </h3>

            <p>
                <strong>Name:</strong>
                {% if user.is_staff %}
                <a href="{% url 'hospital:update' pk=hospital.id %}">{{ hospital.name }}</a>
                {% else %}
                {{ hospital.name }}
                {% endif %}
            </p>
            <p>
                <strong>Address:</strong>
                {{ hospital.number }} {{ hospital.street }} {{ hospital.unit }},
                {{ hospital.city }}, {{ hospital.state }} {{ hospital.zipcode }},
                {{ hospital.country }}
            </p>
            <p>
                <strong>Location:</strong>
                {{ hospital.location }}
            </p>
            <p>
                <strong>Comment:</strong>
                {{ hospital.comment }}
            </p>
            <p>
                <strong>Updated on:</strong>
                {{ hospital.updated_on }}
            </p>
            <p>
                <strong>By:</strong>
                {{ hospital.updated_by }}
            </p>

        </div>
    </div>

    <div class="row">
        <div class="col">

            <h3>
                Equipment:
            </h3>

            <table class="table table-striped table-sm">
                <thead>
                <tr>
                    <th>Name</th>
                    <th>Value</th>
                    <th>Comment</th>
                    <th>Updated on</th>
                    <th>by</th>
                </tr>
                </thead>
                <tbody>
                {% for equipment in hospital.hospitalequipment_set.all %}
                <tr>
                    <td>{{ equipment.equipment.name }}</td>
                    <td>{{ equipment.value }}</td>
                    <td>{{ equipment.comment }}</td>
                    <td>{{ equipment.updated_by }}</td>
                    <td>{{ equipment.updated_on }}</td>
                </tr>
                {% endfor %}
                </tbody>
            </table>

        </div>
    </div>
</div>

{% endblock %}

templates/hospital/hospital_form.html
{% extends "base.html" %}
{% load static %}

{% block head %}
{{ form.media }}
{% endblock %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col">

            <h1>Hospital</h1>

            <form method="POST" class="post-form">
                {% csrf_token %}

                <h3>Details:</h3>

                <table>
                    {{ form }}
                </table>

                <h3>Equipment:</h3>

                {% for form in inlines %}
                <table>
                    {{ form }}
                </table>
                {% endfor %}

                <p>
                    <button type="submit" class="btn btn-primary">Save</button>
                </p>
            </form>
        </div>
    </div>
</div>

{% endblock %}

templates/hospital/hospital_list.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<div class="container">
	<div class="row">
		<div class="col">

			<h1>Hospitals</h1>

            {% if user.is_staff %}
			<p>
				<a href="{% url 'hospital:create' %}">new</a>
			</p>
            {% endif %}
			<table class="table table-striped table-sm">
				<thead>
				<tr>
					<th>Name</th>
					<th>Address</th>
					<th>Comments</th>
					<th>Updated on</th>
					<th>by</th>
				</tr>
				</thead>
				<tbody>
				{% for hospital in hospital_list %}
				<tr>
					<td>
						<a href="{% url 'hospital:detail' pk=hospital.id %}">{{ hospital.name }}</a>
					</td>
					<td>
						{{ hospital.number }} {{ hospital.street }} {{ hospital.unit }},
						{{ hospital.city }}, {{ hospital.state }} {{ hospital.zipcode }},
						{{ hospital.country }}
					</td>
					<td>{{ hospital.comment }}</td>
					<td>{{ hospital.updated_on }}</td>
					<td>{{ hospital.updated_by.username }}</td>
				</tr>
				{% endfor %}
				</tbody>
			</table>
		</div>
	</div>
</div>

{% endblock %}

templates/hospital/hospitalequipment_detail.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<h1>Hospital Equipment</h1>

<div class="container">
    <div class="row">
        <div class="col">

            <h3>Details:</h3>

            <p>
                <strong>Name:</strong>
                <a href="{% url 'hospital:equipment_update' pk=equipment.id %}">{{ equipment.name }}</a>
            </p>
            <p>
                <strong>Type:</strong>
                {{ equipment.etype|get_equipment_type }}
            </p>
        </div>
    </div>
</div>

{% endblock %}

templates/hospital/hospitalequipment_form.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<h1>Hospital Equipment</h1>

<div class="container">
  <form method="POST" class="post-form">
    {% csrf_token %}

    <h3>Details:</h3>

    <table>
      {{ form }}
    </table>

    <p>
      <button type="submit">Save</button>
    </p>
  </form>
</div>

{% endblock %}

templates/hospital/hospitalequipment_list.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<h1>Hospital Equipment</h1>

<div class="container">
	<p>
		<a href="{% url 'hospital:equipment_create' %}">new</a>
	</p>
	<table class="table table-striped table-condensed">
		<thead>
		<tr>
			<th>Name</th>
			<th>Type</th>
		</tr>
		</thead>
		<tbody>
		{% for equipment in equipment_list %}
		<tr>
			<td>
				<a href="{% url 'hospital:equipment_detail' pk=equipment.id %}">{{ equipment.name }}</a>
			</td>
			<td>
				{{ equipment.etype|get_equipment_type }}
			</td>
		</tr>
		{% endfor %}
		</tbody>
	</table>
</div>

{% endblock %}