login/urls.py
from django.conf.urls import url
from django.contrib.admin.views.decorators import staff_member_required

from login import views

app_name = 'login'
urlpatterns = [

    # login/logout
    url(r'^login/$',
        views.LoginView.as_view(),
        name='login'),
    url(r'^logout/$',
        views.LogoutView.as_view(),
        name='logout'),

    # signup
    url(r'^signup/$',
        views.SignupView.as_view(),
        name='signup'),
    
    # User Admin
    
    url(r'^user/$',
        staff_member_required(views.UserAdminListView.as_view()),
        name='user_list'),

    url(r'^user/create/$',
        staff_member_required(views.UserAdminCreateView.as_view()),
        name='user_create'),

    url(r'^user/detail/(?P<pk>[0-9]+)$',
        staff_member_required(views.UserAdminDetailView.as_view()),
        name='user_detail'),

    url(r'^user/update/(?P<pk>[0-9]+)$',
        staff_member_required(views.UserAdminUpdateView.as_view()),
        name='user_update'),

    # Group Admin

    url(r'^group/$',
        staff_member_required(views.GroupAdminListView.as_view()),
        name='group_list'),

    url(r'^group/create/$',
        staff_member_required(views.GroupAdminCreateView.as_view()),
        name='group_create'),

    url(r'^group/detail/(?P<pk>[0-9]+)$',
        staff_member_required(views.GroupAdminDetailView.as_view()),
        name='group_detail'),

    url(r'^group/update/(?P<pk>[0-9]+)$',
        staff_member_required(views.GroupAdminUpdateView.as_view()),
        name='group_update'),

    # client admin
    url(r'^client/$',
        staff_member_required(views.ClientListView.as_view()),
        name='client_list'),

    url(r'^client/detail/(?P<pk>[0-9]+)$',
        staff_member_required(views.ClientDetailView.as_view()),
        name='client_detail'),

    # restart

    url(r'^restart/$',
        views.RestartView.as_view(),
        name='restart'),

    # mqtt login
    
    url(r'^mqtt/login/$',
        views.MQTTLoginView.as_view(),
        name='mqtt_login'),
    url(r'^mqtt/superuser/$',
        views.MQTTSuperuserView.as_view(),
        name='mqtt_superuser'),
    url(r'^mqtt/acl/$',
        views.MQTTAclView.as_view(),
        name='mqtt_acl'),
    
]

hospital/models.py
from enum import Enum

from django.urls import reverse
from django.contrib.gis.db import models
from django.template.defaulttags import register

from emstrack.models import AddressModel, UpdatedByModel


# filters

@register.filter
def get_equipment_type(type):
    return EquipmentType[type].value


# Hospital model

class Hospital(AddressModel,
               UpdatedByModel):
    name = models.CharField(max_length=254, unique=True)

    def save(self, *args, **kwargs):

        # creation?
        created = self.pk is None

        # save to Hospital
        super().save(*args, **kwargs)

        # publish to mqtt
        from mqtt.publish import SingletonPublishClient
        SingletonPublishClient().publish_hospital(self)

        # just created?
        if created:
            # invalidate permissions cache
            from login.permissions import cache_clear
            cache_clear()

    def delete(self, *args, **kwargs):

        # remove from mqtt
        from mqtt.publish import SingletonPublishClient
        SingletonPublishClient().remove_hospital(self)

        # invalidate permissions cache
        from login.permissions import cache_clear
        cache_clear()

        # delete from Hospital
        super().delete(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('hospital:detail', kwargs={'pk': self.id})

    def __str__(self):
        return ('Hospital {}(id={})\n' +
                '   Address: {} {} {}\n' +
                '            {} {} {}\n' +
                '            {} \n' +
                '  Location: {}\n' +
                '   Comment: {}\n' +
                '   Updated: {} by {}').format(self.name,
                                               self.id,
                                               self.number,
                                               self.street,
                                               self.unit,
                                               self.city,
                                               self.state,
                                               self.zipcode,
                                               self.country,
                                               self.location,
                                               self.comment,
                                               self.updated_by,
                                               self.updated_on)


class EquipmentType(Enum):
    B = 'Boolean'
    I = 'Integer'
    S = 'String'


class Equipment(models.Model):
    name = models.CharField(max_length=254, unique=True)

    EQUIPMENT_TYPE_CHOICES = \
        [(m.name, m.value) for m in EquipmentType]
    type = models.CharField(max_length=1,
                            choices=EQUIPMENT_TYPE_CHOICES)

    def __str__(self):
        return "{} ({})".format(self.name, self.type)

    def get_absolute_url(self):
        return reverse('hospital:equipment_detail', kwargs={'pk': self.id})


class HospitalEquipment(UpdatedByModel):
    hospital = models.ForeignKey(Hospital,
                                 on_delete=models.CASCADE)
    equipment = models.ForeignKey(Equipment,
                                  on_delete=models.CASCADE)
    value = models.CharField(max_length=254)

    def save(self, *args, **kwargs):

        # creation?
        created = self.pk is None

        # save to HospitalEquipment
        super().save(*args, **kwargs)
        from mqtt.publish import SingletonPublishClient

        # publish to mqtt
        client = SingletonPublishClient()
        client.publish_hospital_equipment(self)
        if created:
            client.publish_hospital_metadata(self.hospital)

    def delete(self, *args, **kwargs):

        # remove from mqtt
        from mqtt.publish import SingletonPublishClient
        client = SingletonPublishClient()
        client.remove_hospital_equipment(self)
        client.publish_hospital_metadata(self.hospital)

        # delete from HospitalEquipment
        super().delete(*args, **kwargs)

    class Meta:
        unique_together = ('hospital', 'equipment',)

    def __str__(self):
        return "Hospital: {}, Equipment: {}, Count: {}".format(self.hospital, self.equipment, self.value)

login/models.py
from enum import Enum

from django.contrib.gis.db import models

from django.contrib.auth.models import User
from django.contrib.auth.models import Group
from django.core.validators import MinValueValidator
from django.template.defaulttags import register
from django.urls import reverse

from login.permissions import cache_clear


# filters

@register.filter
def get_client_status(key):
    return ClientStatus[key].value


@register.filter
def get_client_activity(key):
    return ClientActivity[key].value


class UserProfile(models.Model):
    user = models.OneToOneField(User,
                                on_delete=models.CASCADE)

    def get_absolute_url(self):
        return reverse('login:user_detail', kwargs={'pk': self.user.id})

    def __str__(self):
        return '{}'.format(self.user)


# GroupProfile

class GroupProfile(models.Model):
    group = models.OneToOneField(Group,
                                 on_delete=models.CASCADE)

    description = models.CharField(max_length=100, blank=True, null=True)
    priority = models.PositiveIntegerField(validators=[MinValueValidator(1)], default=10)

    def get_absolute_url(self):
        return reverse('login:group_detail', kwargs={'pk': self.group.id})

    def __str__(self):
        return '{}: description = {}'.format(self.group, self.description)

    class Meta:
        indexes = [models.Index(fields=['priority'])]


# Group Ambulance and Hospital Permissions

class Permission(models.Model):
    can_read = models.BooleanField(default=True)
    can_write = models.BooleanField(default=False)

    class Meta:
        abstract = True


class UserAmbulancePermission(Permission):
    user = models.ForeignKey(User,
                             on_delete=models.CASCADE)
    ambulance = models.ForeignKey('ambulance.Ambulance',
                                  on_delete=models.CASCADE)

    class Meta:
        unique_together = ('user', 'ambulance')

    def save(self, *args, **kwargs):

        # save to UserAmbulancePermission
        super().save(*args, **kwargs)

        # invalidate permissions cache
        cache_clear()

        # publish to mqtt
        from mqtt.publish import SingletonPublishClient
        SingletonPublishClient().publish_profile(self.user)

    def delete(self, *args, **kwargs):

        # delete from UserAmbulancePermission
        super().delete(*args, **kwargs)

        # invalidate permissions cache
        cache_clear()

        # publish to mqtt
        # does not remove because user still exists!
        from mqtt.publish import SingletonPublishClient
        SingletonPublishClient().publish_profile(self.user)

    def __str__(self):
        return '{}/{}(id={}): read[{}] write[{}]'.format(self.user,
                                                         self.ambulance.identifier,
                                                         self.ambulance.id,
                                                         self.can_read,
                                                         self.can_write)


class UserHospitalPermission(Permission):
    user = models.ForeignKey(User,
                             on_delete=models.CASCADE)
    hospital = models.ForeignKey('hospital.Hospital',
                                 on_delete=models.CASCADE)

    class Meta:
        unique_together = ('user', 'hospital')

    def save(self, *args, **kwargs):

        # save to UserHospitalPermission
        super().save(*args, **kwargs)

        # invalidate permissions cache
        cache_clear()

        # publish to mqtt
        from mqtt.publish import SingletonPublishClient
        SingletonPublishClient().publish_profile(self.user)

    def delete(self, *args, **kwargs):

        # delete from UserHospitalPermission
        super().delete(*args, **kwargs)

        # invalidate permissions cache
        cache_clear()

        # publish to mqtt
        # does not remove because user still exists!
        from mqtt.publish import SingletonPublishClient
        SingletonPublishClient().publish_profile(self.user)

    def __str__(self):
        return '{}/{}(id={}): read[{}] write[{}]'.format(self.user,
                                                         self.hospital.name,
                                                         self.hospital.id,
                                                         self.can_read,
                                                         self.can_write)


class GroupAmbulancePermission(Permission):
    group = models.ForeignKey(Group,
                              on_delete=models.CASCADE)
    ambulance = models.ForeignKey('ambulance.Ambulance',
                                  on_delete=models.CASCADE)

    class Meta:
        unique_together = ('group', 'ambulance')

    def save(self, *args, **kwargs):

        # save to GroupAmbulancePermission
        super().save(*args, **kwargs)

        # invalidate permissions cache
        cache_clear()

        # update all profiles for users in the group
        for user in self.group.user_set.all():
            # publish to mqtt
            from mqtt.publish import SingletonPublishClient
            SingletonPublishClient().publish_profile(user)

    def delete(self, *args, **kwargs):

        # delete from GroupAmbulancePermission
        super().delete(*args, **kwargs)

        # invalidate permissions cache
        cache_clear()

        # update all profiles for users in the group
        for user in self.group.user_set.all():
            # publish to mqtt
            from mqtt.publish import SingletonPublishClient
            SingletonPublishClient().publish_profile(user)

    def __str__(self):
        return '{}/{}(id={}): read[{}] write[{}]'.format(self.group,
                                                         self.ambulance.identifier,
                                                         self.ambulance.id,
                                                         self.can_read,
                                                         self.can_write)


class GroupHospitalPermission(Permission):
    group = models.ForeignKey(Group,
                              on_delete=models.CASCADE)
    hospital = models.ForeignKey('hospital.Hospital',
                                 on_delete=models.CASCADE)

    class Meta:
        unique_together = ('group', 'hospital')

    def save(self, *args, **kwargs):

        # save to GroupHospitalPermission
        super().save(*args, **kwargs)

        # invalidate permissions cache
        cache_clear()

        # update all profiles for users in the group
        for user in self.group.user_set.all():
            # publish to mqtt
            from mqtt.publish import SingletonPublishClient
            SingletonPublishClient().publish_profile(user)

    def delete(self, *args, **kwargs):

        # delete from GroupHospitalPermission
        super().delete(*args, **kwargs)

        # invalidate permissions cache
        cache_clear()

        # update all profiles for users in the group
        for user in self.group.user_set.all():
            # publish to mqtt
            from mqtt.publish import SingletonPublishClient
            SingletonPublishClient().publish_profile(user)

    def __str__(self):
        return '{}/{}(id={}): read[{}] write[{}]'.format(self.group,
                                                         self.hospital.name,
                                                         self.hospital.id,
                                                         self.can_read,
                                                         self.can_write)


# TemporaryPassword

class TemporaryPassword(models.Model):
    user = models.OneToOneField(User,
                                on_delete=models.CASCADE)
    password = models.CharField(max_length=254)
    created_on = models.DateTimeField(auto_now=True)

    def __str__(self):
        return '"{}" (created on: {})'.format(self.password, self.created_on)


# Client status
class ClientStatus(Enum):
    O = 'online'
    F = 'offline'
    D = 'disconnected'


# Client information
class Client(models.Model):

    # NOTE: This shouldn't be needed but django was giving me a hard time
    id = models.AutoField(primary_key=True)

    # WARNING: mqtt client_id's can be up to 65536 bytes!
    client_id = models.CharField(max_length=254, unique=True)

    user = models.ForeignKey(User,
                             on_delete=models.CASCADE)

    CLIENT_STATUS_CHOICES = \
        [(m.name, m.value) for m in ClientStatus]
    status = models.CharField(max_length=1,
                              choices=CLIENT_STATUS_CHOICES)

    ambulance = models.ForeignKey('ambulance.Ambulance',
                                  on_delete=models.CASCADE,
                                  blank=True, null=True)

    hospital = models.ForeignKey('hospital.Hospital',
                                 on_delete=models.CASCADE,
                                 blank=True, null=True)

    updated_on = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.client_id


# Client activity
class ClientActivity(Enum):
    HS = 'handshake'
    AI = 'ambulance login'
    AO = 'ambulance logout'
    TL = 'ambulance stop location'
    SL = 'ambulance start location'
    HI = 'hospital login'
    HO = 'hospital logout'


# Client log
class ClientLog(models.Model):

    client = models.ForeignKey(Client,
                               on_delete=models.CASCADE)

    status = models.CharField(max_length=1,
                              choices=Client.CLIENT_STATUS_CHOICES)

    CLIENT_ACTIVITIES_CHOICES = \
        [(m.name, m.value) for m in ClientActivity]
    activity = models.CharField(max_length=2,
                                choices=CLIENT_ACTIVITIES_CHOICES)

    details = models.CharField(max_length=100, blank=True, null=True)

    updated_on = models.DateTimeField(auto_now=True)

templates/login/client_detail.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col">

            <h1>Client</h1>

            <h3>Details:</h3>

            <p>
                <strong>Client ID:</strong>
                {{ client.client_id }}
            </p>

            <p>
                <strong>User:</strong>
                {{ client.user.username }}
            </p>

            <p>
                <strong>Status:</strong>
                {{ client.status|get_client_status }}
            </p>

            {% if client.ambulance %}
            <p>
                <strong>Ambulance:</strong>
                {{ client.ambulance.identifier }}
            </p>
            {% endif %}

            {% if client.hospital %}
            <p>
                <strong>Hospital:</strong>
                {{ client.hospital.name }}
            </p>
            {% endif %}

            <p>
                <strong>Updated on:</strong>
                {{ client.updated_on }}
            </p>
        </div>
    </div>

    <div class="row">
        <div class="col">

            <h3>Log:</h3>

            <table class="table table-striped table-sm">
                <thead>
                <tr>
                    <th>Status</th>
                    <th>Activity</th>
                    <th>Details</th>
                    <th>Updated On</th>
                </tr>
                </thead>
                <tbody>
                {% for clientlog in clientlog_list %}
                <tr>
                    <td>
                        {{ clientlog.status|get_client_status }}
                    </td>
                    <td>
                        {{ clientlog.activity|get_client_activity }}
                    </td>
                    <td>
                        {{ clientlog.details }}
                    </td>
                    <td>
                        {{ clientlog.updated_on }}
                    </td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

</div>

{% endblock %}

templates/login/client_list.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col">

            <h1>Clients</h1>

            <table class="table table-striped table-sm">
                <thead>
                <tr>
                    <th>Client Id</th>
                    <th>User</th>
                    <th>Status</th>
                    <th>Ambulance</th>
                    <th>Hospital</th>
                    <th>Updated On</th>
                </tr>
                </thead>
                <tbody>
                {% for client in client_list %}
                <tr>
                    <td>
                        <a href="{% url 'login:client_detail' pk=client.id %}">{{ client.client_id }}</a>
                    </td>
                    <td>
                        {{ client.user.username }}
                    </td>
                    <td>
                        {{ client.status|get_client_status }}
                    </td>
                    <td>
                        {{ client.ambulance.identifier }}
                    </td>
                    <td>
                        {{ client.hospital.name }}
                    </td>
                    <td>
                        {{ client.updated_on }}
                    </td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

{% endblock %}

templates/login/group_create.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col">

            <h1>Group</h1>

            <form method="POST" class="post-form">
                {% csrf_token %}

                <h3>Details:</h3>

                <table>
                    {{ form }}
                </table>

                <p>
                    Edit the group after creation to provide more details.
                </p>

                <p>
                    <button type="submit" class="btn btn-primary">Save</button>
                </p>
            </form>
        </div>
    </div>
</div>

{% endblock %}

templates/login/group_detail.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col">

            <h1>Group</h1>

            <h3>Details:</h3>

            <p>
                <strong>Name:</strong>
                <a href="{% url 'login:group_update' pk=group.id %}">{{ group.name }}</a>
            </p>

            <p>
                <strong>Description:</strong>
                {{ group.groupprofile.description }}
            </p>

            <p>
                <strong>Priority</strong>
                {{ group.groupprofile.priority }}
            </p>

        </div>
    </div>

    <div class="row">
        <div class="col">

            <h3>Users:</h3>

            <table class="table table-striped table-sm">
                <thead>
                <tr>
                    <th>Username</th>
                    <th>First</th>
                    <th>Last</th>
                    <th>Email</th>
                </tr>
                </thead>
                <tbody>
                {% for user in user_list %}
                <tr>
                    <td>
                        <a href="{% url 'login:user_detail' pk=user.id %}">{{ user.username }}</a>
                    </td>
                    <td>
                        {{ user.first_name }}
                    </td>
                    <td>
                        {{ user.last_name }}
                    </td>
                    <td>
                        {{ user.email }}
                    </td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

    <div class="row">
        <div class="col">

            <h3>Permissions:</h3>

            <table class="table table-striped table-sm">
                <thead>
                <tr>
                    <th>Ambulance</th>
                    <th>Read</th>
                    <th>Write</th>
                </tr>
                </thead>
                <tbody>
                {% for permission in ambulance_list %}
                <tr>
                    <td> {{ permission.ambulance.identifier }} </td>
                    <td> {{ permission.can_read }} </td>
                    <td> {{ permission.can_write }} </td>
                </tr>
                {% endfor %}
                </tbody>
            </table>

            <table class="table table-striped table-sm">
                <thead>
                <tr>
                    <th>Hospital</th>
                    <th>Read</th>
                    <th>Write</th>
                </tr>
                </thead>
                <tbody>
                {% for permission in hospital_list %}
                <tr>
                    <td> {{ permission.hospital.name }} </td>
                    <td> {{ permission.can_read }} </td>
                    <td> {{ permission.can_write }} </td>
                </tr>
                {% endfor %}
                </tbody>
            </table>

        </div>
    </div>
</div>

{% endblock %}

templates/login/group_form.html
{% extends "base.html" %}
{% load static %}

{% block content %}


<div class="container">
    <div class="row">
        <div class="col">

            <h1>Group</h1>

            <form method="POST" class="post-form">
                {% csrf_token %}

                <h3>Details:</h3>

                <table>
                    {{ form }}
                    {% for form in inlines|slice:":1" %}
                    {{ form }}
                    {% endfor %}
                </table>

                <h3>Permissions:</h3>

                {% for form in inlines|slice:"1:" %}
                <table>
                    {{ form }}
                </table>
                {% endfor %}

                <p>
                    <button type="submit" class="btn btn-primary">Save</button>
                </p>
            </form>
        </div>
    </div>
</div>

{% endblock %}

templates/login/group_list.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-md-6">

            <h1>Groups</h1>

            <p>
                <a href="{% url 'login:group_create' %}">new</a>
            </p>

            <table class="table table-striped table-sm">
                <thead>
                <tr>
                    <th>Name</th>
                    <th>Description</th>
                    <th>Priority</th>
                </tr>
                </thead>
                <tbody>
                {% for group in group_list %}
                <tr>
                    <td>
                        <a href="{% url 'login:group_detail' pk=group.id %}">{{ group.name }}</a>
                    </td>
                    <td>
                        {{ group.groupprofile.description }}
                    </td>
                    <td>
                        {{ group.groupprofile.priority }}
                    </td>
                </tr>
                {% endfor %}
                </tbody>
            </table>

        </div>
    </div>
</div>

{% endblock %}

templates/login/mqtt_login.html
{% extends "base.html" %}
{% load static %}

{% block title %}EMSTrack Login{% endblock %}

{% block head %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/auth.css' %}"/>
{% endblock %}

{% block content %}

    {% if form.errors %}
        <p>Your username and password didn't match. Please try again.</p>
    {% endif %}

    {% if next %}
        {% if user.is_authenticated %}
            <p>
                Your account doesn't have access to this page.
                To proceed, please login with an account that has access.
            </p>
        {% endif %}
    {% endif %}

    <div class="container">
        <form method="post"
              action="{% url 'login:mqtt_login' %}">

            <div class="row input_form">

                <p>
                    {{ form.username }}
                </p>

                <p>
                    {{ form.password }}
                </p>

                <button type="submit"
                        class="btn btn btn-primary btn-success"
                        value="login">Login
                </button>
                <input type="hidden" name="next" value="{{ next }}"/>

            </div>
        </form>
    </div>

{% endblock %}

templates/login/user_detail.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col">

            <h1>User</h1>

            <h3>Details:</h3>

            <p>
                <strong>Username:</strong>
                <a href="{% url 'login:user_update' pk=user.id %}">{{ user.username }}</a>
            </p>
            <p>
                <strong>First:</strong>
                {{ user.first_name }}
            </p>
            <p>
                <strong>Last:</strong>
                {{ user.last_name }}
            </p>
            <p>
                <strong>Email:</strong>
                {{ user.email}}
            </p>
            <p>
                <strong>Staff:</strong>
                {{ user.is_staff }}
            </p>
            <p>
                <strong>Active:</strong>
                {{ user.is_active }}
            </p>
        </div>
    </div>

    <div class="row">
        <div class="col">

            <h3>Groups:</h3>

            <table class="table table-striped table-sm">
                <thead>
                <tr>
                    <th>Name</th>
                    <th>Description</th>
                </tr>
                </thead>
                <tbody>
                {% for group in group_list %}
                <tr>
                    <td>
                        <a href="{% url 'login:group_detail' pk=user.id %}">{{ group.name }}</a>
                    </td>
                    <td>
                        {{ group.groupprofile.description }}
                    </td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

    <div class="row">
        <div class="col">

            <h3>Permissions:</h3>

            <table class="table table-striped table-sm">
                <thead>
                <tr>
                    <th>Ambulance</th>
                    <th>Read</th>
                    <th>Write</th>
                </tr>
                </thead>
                <tbody>
                {% for permission in ambulance_list %}
                <tr>
                    <td> {{ permission.ambulance.identifier }}</td>
                    <td> {{ permission.can_read }}</td>
                    <td> {{ permission.can_write }}</td>
                </tr>
                {% endfor %}
                </tbody>
            </table>

            <table class="table table-striped table-sm">
                <thead>
                <tr>
                    <th>Hospital</th>
                    <th>Read</th>
                    <th>Write</th>
                </tr>
                </thead>
                <tbody>
                {% for permission in hospital_list %}
                <tr>
                    <td> {{ permission.hospital.name }}</td>
                    <td> {{ permission.can_read }}</td>
                    <td> {{ permission.can_write }}</td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

{% endblock %}

templates/login/user_list.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col">

            <h1>Users</h1>

            <p>
                <a href="{% url 'login:user_create' %}">new</a>
            </p>
            <table class="table table-striped table-sm">
                <thead>
                <tr>
                    <th>Username</th>
                    <th>First</th>
                    <th>Last</th>
                    <th>Email</th>
                    <th>Staff</th>
                    <th>Active</th>
                </tr>
                </thead>
                <tbody>
                {% for user in user_list %}
                <tr>
                    <td>
                        <a href="{% url 'login:user_detail' pk=user.id %}">{{ user.username }}</a>
                    </td>
                    <td>
                        {{ user.first_name }}
                    </td>
                    <td>
                        {{ user.last_name }}
                    </td>
                    <td>
                        {{ user.email}}
                    </td>
                    <td>
                        {{ user.is_staff|get_check }}
                    </td>
                    <td>
                        {{ user.is_active|get_check_or_times }}
                    </td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

{% endblock %}