ambulance/urls.py
from django.conf.urls import url
from django.contrib.admin.views.decorators import staff_member_required

from django.contrib.auth.decorators import login_required

from . import views

app_name = 'ambulance'
urlpatterns = [
    
    url(r'^map/$',
        login_required(views.AmbulanceMap.as_view()),
        name="map"),
    
    url(r'^list/$',
        login_required(views.AmbulanceListView.as_view()),
        name="list"),
    
    url(r'^create/$',
        login_required(views.AmbulanceCreateView.as_view()),
        name='create'),
    
    url(r'^detail/(?P<pk>[0-9]+)$',
        login_required(views.AmbulanceDetailView.as_view()),
        name='detail'),

    url(r'^update/(?P<pk>[0-9]+)$',
        login_required(views.AmbulanceUpdateView.as_view()),
        name='update'),

    # Admin

    url(r'^location/list/$',
        staff_member_required(views.LocationAdminListView.as_view()),
        name='location_list'),

    url(r'^location/create$',
        staff_member_required(views.LocationAdminCreateView.as_view()),
        name='location_create'),

    url(r'^location/detail/(?P<pk>[0-9]+)$',
        staff_member_required(views.LocationAdminDetailView.as_view()),
        name='location_detail'),

    url(r'^location/update/(?P<pk>[0-9]+)$',
        staff_member_required(views.LocationAdminUpdateView.as_view()),
        name='location_update'),

    # NEED REVISING
    
    url(r'^call/list/$',
        login_required(views.CallListView.as_view()),
        name="call_list"),

    url(r'call/detail/(?P<pk>\d+)$', 
        login_required(views.CallDetailView.as_view()),
        name='call_detail'),

    url(r'call/abort/(?P<pk>\d+)$',
        login_required(views.CallAbortView.as_view()),
        name='call_abort'),

    # url(r'^admin/$',
    #    login_required(views.AdminView.as_view()),
    #    name="admin"),
    
]

login/urls.py
from django.conf.urls import url
from django.contrib.admin.views.decorators import staff_member_required

from login import views

app_name = 'login'
urlpatterns = [

    # login/logout
    url(r'^login/$',
        views.LoginView.as_view(),
        name='login'),
    url(r'^logout/$',
        views.LogoutView.as_view(),
        name='logout'),

    # signup
    url(r'^signup/$',
        views.SignupView.as_view(),
        name='signup'),
    
    # User Admin
    
    url(r'^user/$',
        staff_member_required(views.UserAdminListView.as_view()),
        name='user_list'),

    url(r'^user/create/$',
        staff_member_required(views.UserAdminCreateView.as_view()),
        name='user_create'),

    url(r'^user/detail/(?P<pk>[0-9]+)$',
        staff_member_required(views.UserAdminDetailView.as_view()),
        name='user_detail'),

    url(r'^user/update/(?P<pk>[0-9]+)$',
        staff_member_required(views.UserAdminUpdateView.as_view()),
        name='user_update'),

    # Group Admin

    url(r'^group/$',
        staff_member_required(views.GroupAdminListView.as_view()),
        name='group_list'),

    url(r'^group/create/$',
        staff_member_required(views.GroupAdminCreateView.as_view()),
        name='group_create'),

    url(r'^group/detail/(?P<pk>[0-9]+)$',
        staff_member_required(views.GroupAdminDetailView.as_view()),
        name='group_detail'),

    url(r'^group/update/(?P<pk>[0-9]+)$',
        staff_member_required(views.GroupAdminUpdateView.as_view()),
        name='group_update'),

    # client admin
    url(r'^client/$',
        staff_member_required(views.ClientListView.as_view()),
        name='client_list'),

    url(r'^client/detail/(?P<pk>[0-9]+)$',
        staff_member_required(views.ClientDetailView.as_view()),
        name='client_detail'),

    # restart

    url(r'^restart/$',
        views.RestartView.as_view(),
        name='restart'),

    # mqtt login
    
    url(r'^mqtt/login/$',
        views.MQTTLoginView.as_view(),
        name='mqtt_login'),
    url(r'^mqtt/superuser/$',
        views.MQTTSuperuserView.as_view(),
        name='mqtt_superuser'),
    url(r'^mqtt/acl/$',
        views.MQTTAclView.as_view(),
        name='mqtt_acl'),
    
]

ambulance/forms.py
from django import forms
from django.contrib.gis.forms import PointField
from django.utils import timezone

from emstrack.forms import LeafletPointWidget

from .models import Ambulance, Call, Location


class AmbulanceCreateForm(forms.ModelForm):
    location = PointField(
        widget=LeafletPointWidget(attrs={'map_width': 500,
                                         'map_height': 300})
    )

    class Meta:
        model = Ambulance
        fields = ['identifier', 'capability', 'status', 'comment', 'location']


class AmbulanceUpdateForm(AmbulanceCreateForm):

    def clean(self):
        # call super
        super().clean()

        # if updating status or location
        if 'status' in self.changed_data or 'location' in self.changed_data:
            # See https://stackoverflow.com/questions/5275476/django-alter-form-data-in-clean-method
            # Mauricio: I think this odd behavior is because timestamp is not present in the form

            # update timestamp as well
            now = timezone.now()
            self.cleaned_data["timestamp"] = now
            self.instance.timestamp = now

        return self.cleaned_data


# Location forms

class LocationAdminCreateForm(forms.ModelForm):
    location = PointField(
        widget=LeafletPointWidget(attrs={'map_width': 500,
                                         'map_height': 300})
    )

    class Meta:
        model = Location
        fields = ['name', 'type',
                  'number', 'street', 'unit', 'neighborhood',
                  'city', 'state', 'zipcode', 'country',
                  'location', 'comment']


class LocationAdminUpdateForm(LocationAdminCreateForm):
    pass


# front end team to choose which fields to display?

class CallCreateForm(forms.ModelForm):
    class Meta:
        model = Call
        fields = '__all__'

# class AmbulanceStatusCreateForm(forms.ModelForm):
#     class Meta:
#         model = AmbulanceStatus
#         fields = '__all__'


# class AmbulanceStatusUpdateForm(forms.ModelForm):
#     class Meta:
#         model = AmbulanceStatus
#         fields = '__all__'


# class AmbulanceCapabilityCreateForm(forms.ModelForm):
#     class Meta:
#         model = AmbulanceCapability
#         fields = '__all__'

ambulance/views.py
import uuid

from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.shortcuts import redirect
from django.views.generic import TemplateView, ListView, \
    DetailView, CreateView, UpdateView
from django.views.generic.detail import BaseDetailView

from .models import Ambulance, AmbulanceCapability, AmbulanceStatus, \
    Call, Location, LocationType, CallStatus, AmbulanceCallStatus

from .forms import AmbulanceCreateForm, AmbulanceUpdateForm, LocationAdminCreateForm, LocationAdminUpdateForm

from emstrack.mixins import BasePermissionMixin, UpdatedByMixin

from emstrack.views import get_page_links, get_page_size_links


# Ambulance views

class AmbulancePermissionMixin(BasePermissionMixin):

    filter_field = 'id'
    profile_field = 'ambulances'
    queryset = Ambulance.objects.all()


class AmbulanceDetailView(LoginRequiredMixin,
                          SuccessMessageMixin,
                          UpdatedByMixin,
                          AmbulancePermissionMixin,
                          DetailView):

    model = Ambulance
    
    def get_context_data(self, **kwargs):

        # add paginated updates to context

        # call supper
        context = super().get_context_data(**kwargs)

        # query
        updates_query = self.object.ambulanceupdate_set.order_by('-timestamp')

        # get current page
        page = self.request.GET.get('page', 1)
        page_size = self.request.GET.get('page_size', 250)
        page_sizes = [250, 500, 1000]

        # paginate
        paginator = Paginator(updates_query, page_size)
        try:
            updates = paginator.page(page)
        except PageNotAnInteger:
            updates = paginator.page(1)
        except EmptyPage:
            updates = paginator.page(paginator.num_pages)

        context['updates'] = updates
        context['page_links'] = get_page_links(self.request, updates)
        context['page_size_links'] = get_page_size_links(self.request, updates, page_sizes)
        context['page_size'] = int(page_size)

        # add ambulance_status
        context['ambulance_status'] = {m.name: m.value
                                       for m in AmbulanceStatus}

        return context


class AmbulanceListView(LoginRequiredMixin,
                        AmbulancePermissionMixin,
                        ListView):
    
    model = Ambulance
    ordering = ['identifier']


class AmbulanceCreateView(LoginRequiredMixin,
                          SuccessMessageMixin,
                          UpdatedByMixin,
                          AmbulancePermissionMixin,
                          CreateView):
    
    model = Ambulance
    form_class = AmbulanceCreateForm

    def get_success_url(self):
        return self.object.get_absolute_url()
    

class AmbulanceUpdateView(LoginRequiredMixin,
                          SuccessMessageMixin,
                          UpdatedByMixin,
                          AmbulancePermissionMixin,
                          UpdateView):
    
    model = Ambulance
    form_class = AmbulanceUpdateForm

    def get_success_url(self):
        return self.object.get_absolute_url()


# Ambulance css information
AmbulanceCSS = {
    'UK': {
        'icon': {
            'iconUrl': '/static/icons/cars/ambulance_blue.svg',
            'iconSize': [15, 30],
        },
        'class': 'btn-primary'
    },
    'AV': {
        'icon': {
            'iconUrl': '/static/icons/cars/ambulance_green.svg',
            'iconSize': [15, 30],
        },
        'class': 'btn-success'
    },
    'OS': {
        'icon': {
            'iconUrl': '/static/icons/cars/ambulance_gray.svg',
            'iconSize': [15, 30],
        },
        'class': 'btn-secondary'
    },
    'PB': {
        'icon': {
            'iconUrl': '/static/icons/cars/ambulance_red.svg',
            'iconSize': [15, 30],
        },
        'class': 'btn-danger'
    },
    'AP': {
        'icon': {
            'iconUrl': '/static/icons/cars/ambulance_orange.svg',
            'iconSize': [15, 30],
        },
        'class': 'btn-warning'
    },
    'HB': {
        'icon': {
            'iconUrl': '/static/icons/cars/ambulance_purple.svg',
            'iconSize': [15, 30],
        },
        'class': 'btn-info'
    },
    'AH': {
        'icon': {
            'iconUrl': '/static/icons/cars/ambulance_yellow.svg',
            'iconSize': [15, 30],
        },
        'class': 'btn-yellow'
    }
}


class AmbulanceMap(TemplateView):
    template_name = 'ambulance/map.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['ambulance_status'] = {m.name: m.value
                                       for m in AmbulanceStatus}
        context['ambulance_capability'] = {m.name: m.value
                                           for m in AmbulanceCapability}
        context['location_type'] = {m.name: m.value
                                    for m in LocationType}
        context['call_status'] = {m.name: m.value
                                  for m in CallStatus}
        context['ambulancecall_status'] = {m.name: m.value
                                           for m in AmbulanceCallStatus}
        context['broker_websockets_host'] = settings.MQTT['BROKER_WEBSOCKETS_HOST']
        context['broker_websockets_port'] = settings.MQTT['BROKER_WEBSOCKETS_PORT']
        context['client_id'] = 'javascript_client_' + uuid.uuid4().hex
        context['ambulance_css'] = AmbulanceCSS
        return context


# Locations

class LocationAdminListView(ListView):
    model = Location


class LocationAdminDetailView(DetailView):
    model = Location


class LocationAdminCreateView(SuccessMessageMixin,
                              UpdatedByMixin,
                              CreateView):
    model = Location
    form_class = LocationAdminCreateForm

    def get_success_message(self, cleaned_data):
        return "Successfully created location '{}'".format(cleaned_data['name'])

    def get_success_url(self):
        return self.object.get_absolute_url()


class LocationAdminUpdateView(SuccessMessageMixin,
                              UpdatedByMixin,
                              UpdateView):
    model = Location
    form_class = LocationAdminUpdateForm

    def get_success_message(self, cleaned_data):
        return "Successfully updated location '{}'".format(cleaned_data['name'])

    def get_success_url(self):
        return self.object.get_absolute_url()


# Calls

# Call permissions
class CallPermissionMixin(BasePermissionMixin):

    filter_field = 'ambulancecall__ambulance_id'
    profile_field = 'ambulances'
    queryset = Call.objects.all()


# Call ListView
class CallListView(LoginRequiredMixin,
                   CallPermissionMixin,
                   ListView):
    model = Call

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        queryset = self.get_queryset()
        context['pending_list'] = queryset.filter(status=CallStatus.P.name)
        context['started_list'] = queryset.filter(status=CallStatus.S.name)
        context['ended_list'] = queryset.filter(status=CallStatus.E.name)
        return context


# Call DetailView
class CallDetailView(LoginRequiredMixin,
                     CallPermissionMixin,
                     SuccessMessageMixin,
                     UpdatedByMixin,
                     DetailView):
    model = Call

    def get_success_url(self):
        return self.object.get_absolute_url()


# Call abort view
class CallAbortView(LoginRequiredMixin,
                    CallPermissionMixin,
                    SuccessMessageMixin,
                    BaseDetailView):
    model = Call

    def get_success_url(self):
        return self.object.get_absolute_url()

    def get(self, request, *args, **kwargs):

        # get call object
        self.object = self.get_object()

        # abort call
        self.object.abort()

        return redirect('ambulance:call_list')

# Admin page
# class AdminView(ListView):
#    model = Call
#   template_name = 'ambulance/dispatch_list.html'
#    context_object_name = "ambulance_call"


# # AmbulanceStatus list page
# class AmbulanceStatusCreateView(CreateView):
#     model = AmbulanceStatus
#     context_object_name = "ambulance_status_form"
#     form_class = AmbulanceStatusCreateForm
#     success_url = reverse_lazy('status')

#     def get_context_data(self, **kwargs):
#         context = super(AmbulanceStatusCreateView, self).get_context_data(**kwargs)
#         context['statuses'] = AmbulanceStatus.objects.all().order_by('id')
#         return context


# # AmbulanceStatus update page
# class AmbulanceStatusUpdateView(UpdateView):
#     model = AmbulanceStatus
#     form_class = AmbulanceStatusUpdateForm
#     template_name = 'ambulances/ambulance_status_edit.html'
#     success_url = reverse_lazy('status')

#     def get_object(self, queryset=None):
#         obj = AmbulanceStatus.objects.get(id=self.kwargs['pk'])
#         return obj

#     def get_context_data(self, **kwargs):
#         context = super(AmbulanceStatusUpdateView, self).get_context_data(**kwargs)
#         context['id'] = self.kwargs['pk']
#         return context


# # Ambulance map page
# class AmbulanceMap(views.JSONResponseMixin, views.AjaxResponseMixin, ListView):
#     template_name = 'ambulances/ambulance_map.html'

#     def get_queryset(self):
#         return Ambulance.objects.all()

templates/ambulance/ambulance_detail.html
{% extends "leaflet/base.html" %}

{% load static %}

{% block leaflethead %}
    <script>
        var ambulance_status = {{ ambulance_status|safe }};
        var ambulance_id = {{ ambulance.id|safe }};
        var APIBaseUrl = '{% url 'index' %}api/';
        var page_size = {{ page_size }};
    </script>
{% endblock %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col">

            <h1>Ambulance</h1>

            <h3>
                Details:
            </h3>

            <p>
                <strong>Identifier:</strong>
                {% if user.is_staff %}
                <a href="{% url 'ambulance:update' pk=ambulance.id %}">{{ ambulance.identifier }}</a>
                {% else %}
                {{ ambulance.identifier }}
                {% endif %}
            </p>
            <p>
                <strong>Capability:</strong>
                {{ ambulance.capability|get_ambulance_capability }}
            </p>
            <p>
                <strong>Status:</strong>
                {{ ambulance.status|get_ambulance_status }}
            </p>
            <p>
                <strong>Comment:</strong>
                {{ ambulance.comment }}
            </p>
            {% if user.is_staff and ambulance.location_client %}
            <p>
                <strong>Location client:</strong>
                <a href="{% url 'login:client_detail' pk=ambulance.location_client.id %}">{{ ambulance.location_client.client_id }}</a>
            </p>
            {% endif %}
            <p>
                <strong>Updated on:</strong>
                {{ ambulance.updated_on }}
            </p>
            <p>
                <strong>By:</strong>
                {{ ambulance.updated_by }}
            </p>
        </div>
    </div>

    <div class="row">
        <div class="col">

            <h3>
                Past Locations:
            </h3>

            <div id="map" class="my-2" style="height: 600px"></div>

        </div>
    </div>

    {% if updates.has_other_pages %}
    <div class="row">
        <div class="col">
            {% include "pagination/numbers.html" %}
        </div>
        <div class="col float-right">
            {% include "pagination/sizes.html" %}
        </div>
    </div>
    {% endif %}

    <div class="row">
        <div class="col">
            <table class="table table-striped table-sm">
                <thead>
                <tr>
                    <th>Status</th>
                    <th>Location</th>
                    <th>Comment</th>
                    <th>Timestamp</th>
                    <th>Updated on</th>
                    <th>by</th>
                </tr>
                </thead>
                <tbody>
                {% for update in updates %}
                <tr>
                    <td>{{ update.status|get_ambulance_status }}</td>
                    <td>{{ update.location }}</td>
                    <td>{{ update.comment }}</td>
                    <td>{{ update.timestamp }}</td>
                    <td>{{ update.updated_on }}</td>
                    <td>{{ update.updated_by }}</td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

    {% if updates.has_other_pages %}
    <div class="row">
        <div class="col">
            {% include "pagination/numbers.html" %}
        </div>
        <div class="col float-right">
            {% include "pagination/sizes.html" %}
        </div>
    </div>
    {% endif %}

</div>

<script src="{% static 'leaflet/js/LeafletWidget.js' %}"></script>
<script src="{% static 'js/ambulance_detail.js' %}"></script>

{% endblock %}

templates/ambulance/ambulance_form.html
{% extends "base.html" %}
{% load static %}

{% block head %}
{{ form.media }}
{% endblock %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col">
            <h1>Ambulance</h1>

            <form method="POST" class="post-form">
                {% csrf_token %}
                <table>
                    {{ form }}
                </table>
                <p>
                    <button type="submit" class="btn btn-primary">Save</button>
                </p>
            </form>
        </div>
    </div>
</div>

{% endblock %}

templates/ambulance/ambulance_list.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col">

            <h1>Ambulances</h1>

            {% if user.is_staff %}
            <p>
                <a href="{% url 'ambulance:create' %}">new</a>
            </p>
            {% endif %}
            <table class="table table-striped table-sm">
                <thead>
                <tr>
                    <th>Identifier</th>
                    <th>Capability</th>
                    <th>Status</th>
                    <th>Comments</th>
                    <th>Updated on</th>
                    <th>by</th>
                </tr>
                </thead>
                <tbody>
                {% for ambulance in ambulance_list %}
                <tr>
                    <td>
                        <a href="{% url 'ambulance:detail' pk=ambulance.id %}">{{ ambulance.identifier }}</a>
                    </td>
                    <td>
                        {{ ambulance.capability|get_ambulance_capability }}
                    </td>
                    <td>
                        {{ ambulance.status|get_ambulance_status }}
                    </td>
                    <td>
                        {{ ambulance.comment }}
                    </td>
                    <td>
                        {{ ambulance.updated_on }}
                    </td>
                    <td>
                        {{ ambulance.updated_by.username }}
                    </td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

{% endblock %}

templates/ambulance/call_detail.html
{% extends "leaflet/base.html" %}

{% load static %}

{% block leaflethead %}
    <script>
        var call_location_x = {{ call.location.x|safe }};
        var call_location_y = {{ call.location.y|safe }};
        var call_id = {{ call.id|safe }};
        var call_status = '{{ call.status|get_call_status|safe }}';
        var ambulances = [];
        var APIBaseUrl = '{% url 'index' %}api/';
        
        {% for ambulancecall in call.ambulancecall_set.all %}
            ambulances.push({{ ambulancecall.ambulance_id }});
        {% endfor %}

    </script>
{% endblock %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col">

            {% if call.status != "E" %}
            <div class="float-right mt-1">
                <form action="{% url 'ambulance:call_abort' pk=call.id %}" method="get">
                    <input type="submit" class="btn btn-danger" value="ABORT CALL">
                </form>
            </div>
            {% endif %}

            <h1>Call</h1>

            <h3>Details:</h3>

            <p>
                <strong>Status:</strong>
                {{ call.status|get_call_status }}
            </p>
            <p>
                <strong>Details:</strong>
                {{ call.details }}
            </p>
            <p>
                <strong>Priority:</strong>
                {{ call.priority }}
            </p>
            <p>
                <strong>Created at:</strong>
                {{ call.created_at }}
            </p>
            <p>
                <strong>Pending at:</strong>
                {{ call.pending_at }}
            </p>
            <p>
                <strong>Started at:</strong>
                {{ call.started_at }}
            </p>
            <p>
                <strong>Ended at:</strong>
                {{ call.ended_at }}
            </p>
        </div>
    </div>

    <div class="row">
        <div class="col">

            <h3>Patients:</h3>

            <table class="table table-striped table-sm">
                <thead>
                <tr>
                    <th>Name</th>
                    <th>Age</th>
                </tr>
                </thead>
                <tbody>
                {% for patient in call.patient_set.all %}
                <tr>
                    <td>
                        {{ patient.name }}
                    </td>
                    <td>
                        {{ patient.age }}
                    </td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

    <div class="row">
        <div class="col">

            <h3>Ambulances:</h3>

            <table class="table table-striped table-sm">
                <thead>
                <tr>
                    <th>Identifier</th>
                    <th>status</th>
                </tr>
                </thead>
                <tbody>
                {% for ambulancecall in call.ambulancecall_set.all %}
                <tr>
                    <td>
                        {{ ambulancecall.ambulance.identifier }}
                    </td>
                    <td>
                        {{ ambulancecall.ambulance.status| get_ambulance_status}}
                    </td>
                </tr>
                {% endfor %}
                </tbody>
            </table>

        </div>
    </div>

    <div class="row">
        <div class="col">

            <h3>Progress:</h3>

            <div id="map" class="my-2" style="height: 600px"></div>

        </div>
    </div>

</div>

<script src="{% static 'leaflet/js/LeafletWidget.js' %}"></script>
<script src="{% static 'js/call_detail.js' %}"></script>

{% endblock %}

templates/ambulance/call_list.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col">

            <h1>Calls</h1>

            <h2>Pending</h2>

            <table class="table table-striped table-sm">
                <thead>
                    <tr>
                        <th>Call ID</th>
                        <th>Details</th>
                        <th>Priority</th>
                        <th>Ambulances</th>
                        <th>Timestamp</th>
                    </tr>
                </thead>
                <tbody>
                    {% for call in pending_list %}
                        <tr>
                            <td><a href="{% url 'ambulance:call_detail' pk=call.id %}">{{ call.id }}</a></td>
                            <td>{{ call.details }}</td>
                            <td>{{ call.priority }}</td>
                            <td>
                            {% for ambulancecall in call.ambulancecall_set.all %}
                            {{ ambulancecall.ambulance.identifier }}
                            {% endfor %}
                            </td>
                            <td>{{ call.pending_at }}</td>
                        </tr>

                    {% endfor %}
                </tbody>
            </table>

            <h2>Started</h2>

            <table class="table table-striped table-sm">
                <thead>
                    <tr>
                        <th>Call ID</th>
                        <th>Details</th>
                        <th>Priority</th>
                        <th>Ambulances</th>
                        <th>Timestamp</th>
                    </tr>
                </thead>
                <tbody>
                    {% for call in started_list %}
                        <tr>
                            <td><a href="{% url 'ambulance:call_detail' pk=call.id %}">{{ call.id }}</a></td>
                            <td>{{ call.details }}</td>
                            <td>{{ call.priority }}</td>
                            <td>
                            {% for ambulancecall in call.ambulancecall_set.all %}
                            {{ ambulancecall.ambulance.identifier }}
                            {% endfor %}
                            </td>
                            <td>{{ call.started_at }}</td>
                        </tr>

                    {% endfor %}
                </tbody>
            </table>

            <h2>Ended</h2>

            <table class="table table-striped table-sm">
                <thead>
                    <tr>
                        <th>Call ID</th>
                        <th>Details</th>
                        <th>Priority</th>
                        <th>Timestamp</th>
                    </tr>
                </thead>
                <tbody>
                    {% for call in ended_list %}
                        <tr>
                            <td><a href="{% url 'ambulance:call_detail' pk=call.id %}">{{ call.id }}</a></td>
                            <td>{{ call.details }}</td>
                            <td>{{ call.priority }}</td>
                            <td>{{ call.ended_at }}</td>
                        </tr>

                    {% endfor %}
                </tbody>
            </table>

        </div>
    </div>
</div>

{% endblock %}

templates/ambulance/location_detail.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col">

            <h1>Location</h1>

            <h3>Details:</h3>

            <p>
                <strong>Name:</strong>
                <a href="{% url 'ambulance:location_update' pk=location.id %}">{{ location.name }}</a>
            </p>
            <p>
                <strong>Type:</strong>
                {{ location.type|get_location_type }}
            </p>
            <p>
                <strong>Address:</strong>
                {{ location.number }} {{ location.street }} {{ location.unit }},
                {{ location.city }}, {{ location.state }} {{ location.zipcode }},
                {{ location.country }}
            </p>
            <p>
                <strong>Location:</strong>
                {{ location.location }}
            </p>
            <p>
                <strong>Comment:</strong>
                {{ location.comment }}
            </p>
            <p>
                <strong>Updated on:</strong>
                {{ location.updated_on }}
            </p>
            <p>
                <strong>By:</strong>
                {{ location.updated_by }}
            </p>
            
        </div>
    </div>
</div>

{% endblock %}

templates/ambulance/location_list.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<div class="container">
	<div class="row">
		<div class="col">

			<h1>Locations</h1>

			<p>
				<a href="{% url 'ambulance:location_create' %}">new</a>
			</p>
			<table class="table table-striped table-sm">
				<thead>
				<tr>
					<th>Name</th>
					<th>Type</th>
					<th>Address</th>
					<th>Comments</th>
					<th>Updated on</th>
					<th>by</th>
				</tr>
				</thead>
				<tbody>
				{% for location in location_list %}
				<tr>
					<td>
						<a href="{% url 'ambulance:location_detail' pk=location.id %}">{{ location.name }}</a>
					</td>
					<td>
						{{ location.type|get_location_type }}
					</td>
					<td>
						{{ location.number }} {{ location.street }} {{ location.unit }},
						{{ location.city }}, {{ location.state }} {{ location.zipcode }},
						{{ location.country }}
					</td>
					<td>{{ location.comment }}</td>
					<td>{{ location.updated_on }}</td>
					<td>{{ location.updated_by.username }}</td>
				</tr>
				{% endfor %}
				</tbody>
			</table>
		</div>
	</div>
</div>

{% endblock %}