ambulance/urls.py
from django.conf.urls import url
from django.contrib.admin.views.decorators import staff_member_required

from django.contrib.auth.decorators import login_required

from . import views

app_name = 'ambulance'
urlpatterns = [
    
    url(r'^map/$',
        login_required(views.AmbulanceMap.as_view()),
        name="map"),
    
    url(r'^list/$',
        login_required(views.AmbulanceListView.as_view()),
        name="list"),
    
    url(r'^create/$',
        login_required(views.AmbulanceCreateView.as_view()),
        name='create'),
    
    url(r'^detail/(?P<pk>[0-9]+)$',
        login_required(views.AmbulanceDetailView.as_view()),
        name='detail'),

    url(r'^update/(?P<pk>[0-9]+)$',
        login_required(views.AmbulanceUpdateView.as_view()),
        name='update'),

    # Admin

    url(r'^location/list/$',
        staff_member_required(views.LocationAdminListView.as_view()),
        name='location_list'),

    url(r'^location/create$',
        staff_member_required(views.LocationAdminCreateView.as_view()),
        name='location_create'),

    url(r'^location/detail/(?P<pk>[0-9]+)$',
        staff_member_required(views.LocationAdminDetailView.as_view()),
        name='location_detail'),

    url(r'^location/update/(?P<pk>[0-9]+)$',
        staff_member_required(views.LocationAdminUpdateView.as_view()),
        name='location_update'),

    # NEED REVISING
    
    url(r'^call/list/$',
        login_required(views.CallListView.as_view()),
        name="call_list"),

    url(r'call/detail/(?P<pk>\d+)$', 
        login_required(views.CallDetailView.as_view()),
        name='call_detail'),

    url(r'call/abort/(?P<pk>\d+)$',
        login_required(views.CallAbortView.as_view()),
        name='call_abort'),

    # url(r'^admin/$',
    #    login_required(views.AdminView.as_view()),
    #    name="admin"),
    
]

hospital/urls.py
from django.conf.urls import url, include
from django.contrib.admin.views.decorators import staff_member_required

from django.contrib.auth.decorators import login_required

from . import views

app_name = 'hospital'
urlpatterns = [

    url(r'^list/$',
        login_required(views.HospitalListView.as_view()),
        name="list"),

    url(r'^create/$',
        login_required(views.HospitalCreateView.as_view()),
        name="create"),
    
    url(r'^detail/(?P<pk>[0-9]+)$',
        login_required(views.HospitalDetailView.as_view()),
        name="detail"),

    url(r'^update/(?P<pk>[0-9]+)$',
        login_required(views.HospitalUpdateView.as_view()),
        name="update"),

    # Admin

    url(r'^equipment/list$',
        staff_member_required(views.EquipmentAdminListView.as_view()),
        name='equipment_list'),

    url(r'^equipment/create$',
        staff_member_required(views.EquipmentAdminCreateView.as_view()),
        name='equipment_create'),

    url(r'^equipment/detail/(?P<pk>[0-9]+)$',
        staff_member_required(views.EquipmentAdminDetailView.as_view()),
        name='equipment_detail'),

    url(r'^equipment/update/(?P<pk>[0-9]+)$',
        staff_member_required(views.EquipmentAdminUpdateView.as_view()),
        name='equipment_update'),

]

login/urls.py
from django.conf.urls import url
from django.contrib.admin.views.decorators import staff_member_required

from login import views

app_name = 'login'
urlpatterns = [

    # login/logout
    url(r'^login/$',
        views.LoginView.as_view(),
        name='login'),
    url(r'^logout/$',
        views.LogoutView.as_view(),
        name='logout'),

    # signup
    url(r'^signup/$',
        views.SignupView.as_view(),
        name='signup'),
    
    # User Admin
    
    url(r'^user/$',
        staff_member_required(views.UserAdminListView.as_view()),
        name='user_list'),

    url(r'^user/create/$',
        staff_member_required(views.UserAdminCreateView.as_view()),
        name='user_create'),

    url(r'^user/detail/(?P<pk>[0-9]+)$',
        staff_member_required(views.UserAdminDetailView.as_view()),
        name='user_detail'),

    url(r'^user/update/(?P<pk>[0-9]+)$',
        staff_member_required(views.UserAdminUpdateView.as_view()),
        name='user_update'),

    # Group Admin

    url(r'^group/$',
        staff_member_required(views.GroupAdminListView.as_view()),
        name='group_list'),

    url(r'^group/create/$',
        staff_member_required(views.GroupAdminCreateView.as_view()),
        name='group_create'),

    url(r'^group/detail/(?P<pk>[0-9]+)$',
        staff_member_required(views.GroupAdminDetailView.as_view()),
        name='group_detail'),

    url(r'^group/update/(?P<pk>[0-9]+)$',
        staff_member_required(views.GroupAdminUpdateView.as_view()),
        name='group_update'),

    # client admin
    url(r'^client/$',
        staff_member_required(views.ClientListView.as_view()),
        name='client_list'),

    url(r'^client/detail/(?P<pk>[0-9]+)$',
        staff_member_required(views.ClientDetailView.as_view()),
        name='client_detail'),

    # restart

    url(r'^restart/$',
        views.RestartView.as_view(),
        name='restart'),

    # mqtt login
    
    url(r'^mqtt/login/$',
        views.MQTTLoginView.as_view(),
        name='mqtt_login'),
    url(r'^mqtt/superuser/$',
        views.MQTTSuperuserView.as_view(),
        name='mqtt_superuser'),
    url(r'^mqtt/acl/$',
        views.MQTTAclView.as_view(),
        name='mqtt_acl'),
    
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewpoint" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <!--
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/btn-yellow.css' %}">

    <!-- JQuery and Bootstrap js -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"
            integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
            integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
            crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
            integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
            crossorigin="anonymous"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.0.12/js/all.js"></script>

    <!-- title -->
    <title>{% block title %}EMSTrack - Ambulance Tracker{% endblock %}</title>
    {% block head %}
    {% endblock %}
</head>

<body>

<!-- Navigation Bar -->
<nav class="navbar navbar-expand-md navbar-dark bg-dark"
     id="base-navbar">

    <!-- Navbar brand -->
    <a class="navbar-brand" href="{% url 'index' %}">EMSTrack</a>

    <!-- Navbar toggle -->
    <button class="navbar-toggler" type="button" data-toggle="collapse"
            data-target="#myNavbar" aria-controls="navbarSupportedContent"
            aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <!-- Navbar Menu -->
    <div class="collapse navbar-collapse" id="myNavbar">
        {% if request.user.is_authenticated %}
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'ambulance:map' %}">
                    <span class="fas fa-globe"></span>
                    Map
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'ambulance:call_list' %}">
                    <span class="fas fa-phone"></span>
                    Calls
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'ambulance:list' %}">
                    <span class="fas fa-ambulance"></span>
                    Ambulances
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'hospital:list' %}">
                    <span class="fas fa-hospital"></span>
                    Hospitals
                </a>
            </li>
        </ul>
        {% endif %}
        <ul class="navbar-nav ml-auto">
            {% if request.user.is_authenticated %}
            {% if request.user.is_staff %}
            <li class="nav-item dropdown" id="navitemDropdown">
                <a class="nav-link dropdown-toggle"
                   id="navbarDropdown"
                   role="button" data-toggle="dropdown" aria-haspopup="true"
                   aria-expanded="false"
                   href="#">
                    <span class="fas fa-wrench"></span>
                    Admin
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{% url 'login:user_list' %}">Users</a>
                    <a class="dropdown-item" href="{% url 'login:group_list' %}">Groups</a>
                    <a class="dropdown-item" href="{% url 'hospital:equipment_list' %}">Equipment</a>
                    <a class="dropdown-item" href="{% url 'ambulance:location_list' %}">Locations</a>
                    <a class="dropdown-item" href="{% url 'login:client_list' %}">Clients</a>
                    <a class="dropdown-item" href="{% url 'login:restart' %}?next={{ request.path }}">Reinitialize</a>
                </div>
            </li>
            {% endif %}
            <li class="nav-item dropdown" id="navitemAccountDropdown">
                <a class="nav-link dropdown-toggle"
                   id="navbarAccountDropdown"
                   role="button" data-toggle="dropdown" aria-haspopup="true"
                   aria-expanded="false"
                   href="#">
                    <span class="fas fa-user"></span>
                    Account
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarAccountDropdown">
                    <a class="dropdown-item" href="{% url 'password_change' %}">Change password</a>
                </div>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'login:logout' %}">
                    <span class="fas fa-sign-out-alt"></span>
                    &nbsp;Logout {{request.user.first_name}}
                </a>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'login:signup' %}">
                    <span class="fas fa-user-plus"></span>&nbsp;
                    Sign Up
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'login:login' %}"
                   href="#">
                    <span class="fas fa-sign-in-alt"></span>&nbsp;
                    Login
                </a>
            </li>
            {% endif %}
        </ul>
    </div>

</nav>

<div class="container">
    <!-- Messages -->
    {% include 'messages.html' %}
</div>

<!-- TODO: Set timezone in settings/defaults -->

<!-- Content block -->
{% load tz %}
{% timezone "America/Tijuana" %}
{% block content %}
{% endblock %}
{% endtimezone %}

<footer class="footer">
    {% block footer %}
    {% endblock %}
</footer>

<script>

    // make current page active
    var pathname = window.location.pathname;

    // exclude home page
    if (pathname != '/') {
        // Make current page active
        $('.nav-item a[href^="' + pathname + '"]').addClass('nav-item active');

        if ((pathname == "{% url 'login:user_list' %}") ||
            (pathname == "{% url 'login:group_list' %}") ||
            (pathname == "{% url 'hospital:equipment_list' %}") ||
            (pathname == "{% url 'ambulance:location_list' %}")) {

            // Make admin menu active
            $('#navitemDropdown').addClass('nav-item active');

        }

    }

</script>

</body>
</html>

templates/base_leaflet.html
{% extends "base.html" %}

{% block head %}
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.3.1/dist/leaflet.css"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/leaflet.draw/1.0.2/leaflet.draw.css"/>
<script src="https://unpkg.com/leaflet@1.3.1/dist/leaflet.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/leaflet.draw/1.0.2/leaflet.draw.js"></script>
{% block leaflethead %}
{% endblock %}
{% endblock %}

templates/homepage.html
<!-- Homepage contents -->

<div class="container">
    <div class="row">
        <div class="col">

            <h1>EMSTrack</h1>

            <h3>Welcome to EMSTrack.</h3>

            <p>
                Some text explaining what this is all about.
            </p>

            <h3>Mission</h3>

            <p>
                Some text explaining what this is all about.
            </p>

            <h3>Contact</h3>

            <p>
                How to contact.
            </p>

        </div>
    </div>
</div>

templates/index.html
{% extends "base.html" %}
{% load static %}

{% block content %}

{% include 'homepage.html' %}

<!-- Modal for signup and login -->

<div class="modal" tabindex="-1" role="dialog" id="loginModal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 id="loginTitle" class="modal-title">EMSTrack Login</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">

                {% if form.non_field_errors %}
                <div class="alert alert-danger alert-dismissible" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    {{ form.non_field_errors }}
                </div>
                {% endif %}

                <form class="form-signin"
                      id="signInForm"
                      method="post"
                      action="{% url 'login:login' %}">
                    {% csrf_token %}

                    {% for field in form %}
                    <div class="form-group">
                        {{ field.label_tag }}
                        {{ field }}
                        {% if field.help_text %}
                        <p>
                            <small style="color: grey">{{ field.help_text }}</small>
                        </p>
                        {% endif %}
                        {% for error in field.errors %}
                        <div class="alert alert-danger alert-dismissible" role="alert">
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                            {{ error }}
                        </div>
                        {% endfor %}
                    </div>
                    {% endfor %}

                    <a id="passwordReset" href="{% url 'password_reset' %}">Forgot Password?</a>

                    <input type="hidden" name="next" value="{{ next }}"/>

                </form>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" id="submitButton">Login</button>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

<script>

    // Ready function
    $(function () {

        $("#submitButton").on('click', function() {
            $("#signInForm").submit();
        });

        // Should start up modal?
        var pathname = window.location.pathname;
        console.log('pathname = ' + pathname);
        if (pathname == '/auth/login/') {

            // bring up modal
            $('#loginModal').modal({
                keyboard: false
            });

        } else if (pathname == '/auth/signup/') {

            // adjust modal
            $('#loginTitle').html('EMSTrack Signup');
            $('#signInForm').attr('action', '{% url 'login:signup' %}');
            $('#passwordReset').hide();
            $('#submitButton').html('Signup');

            // bring up modal
            $('#loginModal').modal({
                keyboard: false
            });

        }

    });

</script>

{% endblock %}

templates/leaflet.html
{% extends "base.html" %}

{% block head %}
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.3.1/dist/leaflet.css"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/leaflet.draw/1.0.2/leaflet.draw.css"/>
<script src="https://unpkg.com/leaflet@1.3.1/dist/leaflet.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/leaflet.draw/1.0.2/leaflet.draw.js"></script>
{% block leaflethead %}
{% endblock %}
{% endblock %}

templates/leaflet_point_widged.html
{% load i18n l10n static %}
<style type="text/css">
    {% block map_css %}{% get_current_language_bidi as LANGUAGE_BIDI %}
    #{{ id }}_div_map {
        position: absolute;
        vertical-align: top;
        float: {{ LANGUAGE_BIDI|yesno:"right,left" }};
    }

    {% if not display_raw %}#{{ id }} { display: none; }{% endif %}

    {% endblock %}
</style>

<div style="display: block">

    <div id="{{ id }}_div_coords">
        <label class="{{ id }}_coords_label">Latitude:</label>
        <input type="text" id="{{ id }}_lat" name="{{ name }}_lat" disabled>
        <br/>
        <label class="{{ id }}_coords_label">Longitude:</label>
        <input type="text" id="{{ id }}_lng" name="{{ name }}_lng" disabled>
        {% if display_raw %}<p>{% trans "Debugging window (serialized value)" %}</p>{% endif %}
        <textarea id="{{ id }}" class="vSerializedField required" cols="150" rows="10"
                  name="{{ name }}">{{ serialized }}</textarea>
    </div>

    <div id="{{ id }}_div_map">
        <div id="{{ id }}_map"></div>
    </div>

</div>

<script type="text/javascript">
    {% block map_options %}
        var map_options = {};
    {% endblock %}

    // has point
    var point = {
        {% if point %}
            x: {{ point.x }},
            y: {{ point.y }},
            {% if point.z %}
                z: {{ point.z }},
            {% else %}
                z: 0,
            {% endif %}
            srid: {{ point.srid }}
                {% else %}
            x: -117.0037100,
            y: 32.5027000,
            z: 0,
            srid: 4326
        {% endif %}
    };

    {% block options %}
        var options = {
            geom_name: '{{ geom_type }}',
            id: '{{ id }}',
            id_lat: '{{ id }}_lat',
            id_lng: '{{ id }}_lng',
            map_id: '{{ id }}_map',
            map_options: map_options,
            map_srid: {{ map_srid|unlocalize }},
            name: '{{ name }}',
            lat: point.y,
            lng: point.x,
            point: [point.y, point.x],
        };
    {% endblock %}

    // Create widget
    var {{ module }} = new LeafletPointWidget(options);

</script>

templates/messages.html
<!-- Django messages using bootstrap
  -- From: https://simpleisbetterthancomplex.com/tips/2016/09/06/django-tip-14-messages-framework.html
  -->
{% for message in messages %}
<div class="alert {{ message.tags }} alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
    {{ message }}
</div>
{% endfor %}

templates/modal.html
{% extends "base.html" %}

{% block content %}

<!-- Modal window -->

<div class="modal" tabindex="-1" role="dialog" id="dialogModal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 id="dialogTitle" class="modal-title">{{ title }}</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">

                {% if form.non_field_errors %}
                <div class="alert alert-danger alert-dismissible" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    {{ form.non_field_errors }}
                </div>
                {% endif %}

                <form class="form-modal"
                      id="modalForm"
                      method="post"
                      action="{{ request.get_full_path }}">
                    {% csrf_token %}

                    {{ foreword|safe }}

                    {% for field in form %}
                    <div class="form-group">
                        {{ field.label_tag }}
                        {{ field }}
                        {% if field.help_text %}
                        <p>
                            <small style="color: grey">{{ field.help_text }}</small>
                        </p>
                        {% endif %}
                        {% for error in field.errors %}
                        <div class="alert alert-danger alert-dismissible" role="alert">
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                            {{ error }}
                        </div>
                        {% endfor %}
                    </div>
                    {% endfor %}

                    {{ afterword|safe }}

                    <input type="hidden" name="next" value="{{ next }}"/>

                </form>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" id="submitButton">OK</button>
                <button type="button" class="btn btn-secondary" id="cancelButton" data-dismiss="modal">Cancel</button>
            </div>
        </div>
    </div>
</div>

<script>

    // Ready function
    $(function () {

        // wire submit button
        $("#submitButton").on('click', function() {
            $("#modalForm").submit();
        });

        // wire cancel button
        $("#cancelButton").on('click', function() {
            window.location.href = "{{ next }}";
        });

        // bring up modal
        $('#dialogModal').modal({
            keyboard: false
        });

    });

</script>
  
{% endblock %}